### PR TITLE
[unitaryhack] Optimizing Qiskit circuit export time by eliminating redundant Qubit instantiations.

### PR DESCRIPTION
**Pull request by upsideon**
### Summary

Fixes [orquestra-core/#12](https://github.com/zapatacomputing/orquestra-core/issues/12) by optimizing the code used to export circuits in Qiskit format. In particular, time was saved by eliminating redundant instantiations of `qiskit.circuit.Qubit`. If you'd like to read about the process of determining the cause and resolving this performance bug, feel free to reference the details section below.

### Details

Profiling via `cProfile` revealed that the majority of time was being spent on calls to the `qiskit.circuit.Qubit` constructor. The profiling snippet below is from exporting a circuit consisting of only 500 qubits, but note that there are 37,522,390 calls to the `__init__` function in `qiskit/circuit/quantumregister.py`.

```
Fri Jun 10 23:39:28 2022    profile_stats_no_changes

         344484238 function calls (340485361 primitive calls) in 210.444 seconds

   Ordered by: cumulative time
   List reduced from 908 to 15 due to restriction <15>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     19/1    0.000    0.000  210.674  210.674 {built-in method builtins.exec}
        1    0.009    0.009  210.674  210.674 <string>:1(<module>)
        1    0.026    0.026  210.665  210.665 zapata-qiskit-profiling.py:30(run_benchmarks_for_circuit_conversion)
        6    0.141    0.023  209.018   34.836 zapata-qiskit-profiling.py:20(timer)
        5    0.044    0.009  185.571   37.114 /home/user/anaconda3/lib/python3.8/site-packages/orquestra/integrations/qiskit/conversions/_circuit_conversions.py:97(export_to_qiskit)
        5    0.158    0.032  184.018   36.804 /home/user/anaconda3/lib/python3.8/site-packages/orquestra/integrations/qiskit/conversions/_circuit_conversions.py:102(<listcomp>)
    50000    0.073    0.000  183.840    0.004 /home/user/anaconda3/lib/python3.8/site-packages/orquestra/integrations/qiskit/conversions/_circuit_conversions.py:116(_export_gate_to_qiskit)
    50000    0.410    0.000  183.767    0.004 /home/user/anaconda3/lib/python3.8/site-packages/orquestra/integrations/qiskit/conversions/_circuit_conversions.py:143(_export_gate_via_mapping)
    50000    0.090    0.000  180.841    0.004 /home/user/anaconda3/lib/python3.8/site-packages/orquestra/integrations/qiskit/conversions/_circuit_conversions.py:154(<listcomp>)
    74890    0.292    0.000  180.751    0.002 /home/user/anaconda3/lib/python3.8/site-packages/orquestra/integrations/qiskit/conversions/_circuit_conversions.py:24(qiskit_qubit)
    74895    0.793    0.000  180.202    0.002 /home/user/anaconda3/lib/python3.8/site-packages/qiskit/circuit/register.py:40(__init__)
    74895   16.427    0.000  179.204    0.002 /home/user/anaconda3/lib/python3.8/site-packages/qiskit/circuit/register.py:120(<listcomp>)
 37522390   63.181    0.000  163.044    0.000 /home/user/anaconda3/lib/python3.8/site-packages/qiskit/circuit/quantumregister.py:26(__init__)
 37522390   63.764    0.000   96.901    0.000 /home/user/anaconda3/lib/python3.8/site-packages/qiskit/circuit/bit.py:26(__init__)
39259889/39258624   11.560    0.000   15.591    0.000 {built-in method builtins.hash}
```

Inspecting the code revealed that fresh instances of `Qubit` were being [generated for every gate applied to them](https://github.com/zapatacomputing/orquestra-qiskit/blob/1e1f36a4700d82efa5e13ad8d906cd5f610ff7cc/src/orquestra/integrations/qiskit/conversions/_circuit_conversions.py#L155) via the `qiskit_qubit` function [here](https://github.com/zapatacomputing/orquestra-qiskit/blob/1e1f36a4700d82efa5e13ad8d906cd5f610ff7cc/src/orquestra/integrations/qiskit/conversions/_circuit_conversions.py#L24). Within `qiskit_qubit`, a new instance of `QuantumRegister` was being initialized for every `Qubit`. As initializing a `QuantumRegister` results in [initialization](https://github.com/Qiskit/qiskit-terra/blob/a18df1456c79dbbd52dae1bd1185c68a0b3e891a/qiskit/circuit/register.py#L124) of a number of underlying `Qubit` instances equal to the size of the register, the total number of `Qubit` instances created per gate was the square of the number of qubits in the circuit.

The solution here was to only create a single instance of `QuantumRegister` per circuit and reference the underlying `Qubit` instances when required via indexing. This guarantees that only a constant number of `Qubit` instances are created. Following implementation, executing the timing code from the linked issue results in the following output:

```
n_qubits:  5
qiskit 0.2709817409515381 0.12168068885803222
cirq 0.4396024227142334 0.1374577045440674
pyquil 0.1780447006225586 0.5983283519744873
n_qubits:  105
qiskit 0.3371572971343994 0.11204299926757813
cirq 0.5949974536895752 0.14093375205993652
pyquil 0.18690004348754882 0.7805288314819336
n_qubits:  305
qiskit 0.42797484397888186 0.13844518661499022
cirq 0.7832437038421631 0.1853236198425293
pyquil 0.23417401313781738 0.8129024982452393
n_qubits:  605
qiskit 0.3320937156677246 0.11168928146362304
cirq 0.7333312034606934 0.14465065002441407
pyquil 0.18884568214416503 0.6695568084716796
n_qubits:  905
qiskit 0.3336315155029297 0.11276893615722657
cirq 0.7131058216094971 0.13993406295776367
pyquil 0.17846603393554689 0.6315788269042969
```

This demonstrates that the Qiskit export time is now in line with that of Cirq and PyQuil.

### CODE REVIEW

**Review by mstechly — APPROVED** [review]

**Comment by mstechly** [comment]
Thanks a lot, looks good!
However, I see the tests are failing for some reason, though I think it's unrelated?
@AthenaCaesura I know you have worked on some `qiskit`-related code recently, could you take a look if these failures look familiar?

**Comment by mstechly** [comment]
@upsideon It seems to be something with your code though, as I've ran tests on the `main` branch and they are passing without issues:
https://github.com/zapatacomputing/orquestra-qiskit/runs/6843056880?check_suite_focus=true
I don't have idea what the reason might be, though. In order to run tests it you would need to set an environmental variable: `ZAPATA_IBM_API_TOKEN` – please use your own token for this.

**Comment by upsideon** [comment]
@mstechly When I set `ZAPATA_IBMQ_API_TOKEN` to my personal API token and run the tests locally on my branch, they all pass. This leads me to believe that the problem wasn't triggered by code changes. If you were to run the tests locally after pulling down my branch, I believe you'd obtain the same results. If we look at the error we receive for all of the test failures:

```
qiskit.providers.ibmq.api.exceptions.RequestsApiError: '400 Client Error: Bad Request for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. API key not found., Error code: 3402.'
```
The `3402` error code indicates that the API token should be regenerated as a solution according to the [IBM Quantum documentation](https://quantum-computing.ibm.com/lab/docs/iql/manage/errors). This leaves me with two possible candidates for the CI failure:

- The Zapata API token used by the CI builds was expired at the time my build ran, but it was regenerated by the time your build was executed using `main`. The regeneration could have occurred if Zapata has an automatic process for generating fresh secrets  for CI when they become expired.
- IBM Quantum experienced a service degradation during the time that my build was executing.

The first possibility seems unlikely and if the Zapata CI secrets are regenerated manually then we can eliminate it entirely. The second possibility is most probable as service degradations aren't unheard of. My recommendation would be that we restart the build (I'm unable to do this, so I'll need your help) to confirm or deny whether this is a persistent problem with the branch or a one time failure.

**Comment by mstechly** [comment]
@upsideon Thanks for this detailed analysis!
I just re-ran the tests, but unfortunately they failed again 🤔 
When running locally I also got similar errors, but running it from `main` doesn't cause the issues, which makes me suspicious about the hypothesis that it's our API key, and that there's something wrong with this branch (even though I have no idea what this could be). Perhaps it's something with our CICD setup 🤷‍♂️ 
Anyway, I won't have time over the weekend to look closer, we'll look at this again on Monday.
Sorry for the delay!

**Comment by upsideon** [comment]
@mstechly Thank you for your help! No worries about not being able to take another look until Monday. I had no expectations to receive a response during the weekend. It's disconcerting that running locally failed for you and it makes me wonder why it works for me given we're using the same branch. I'll have to consider this problem further, but first I'll have to find a way to reproduce what we're seeing in CI locally.

**Comment by upsideon** [comment]
For some added context, the `main` build has a [secret source set](https://github.com/zapatacomputing/orquestra-qiskit/runs/6844347486?check_suite_focus=true#step:1:31) while the build for this branch [does not have one set](https://github.com/zapatacomputing/orquestra-qiskit/runs/6844264508?check_suite_focus=true#step:1:31). That leads to the `ZAPATA_IBMQ_API_TOKEN` environment value being set for the `main` [build](https://github.com/zapatacomputing/orquestra-qiskit/runs/6844347486?check_suite_focus=true#step:4:16), but not the branch [build](https://github.com/zapatacomputing/orquestra-qiskit/runs/6844264508?check_suite_focus=true#step:4:16).

**Comment by mstechly** [comment]
@upsideon there is a setting which doesn't allow to use secrets for PRs created from a fork. At least now it's not a mystery, I just need to figure out a workaround. Stay tuned!

**Comment by mstechly** [comment]
@upsideon I have not found any reasonable, low-effort way around it, so I used my admin privileges to merge this 🤷‍♂️ 
Thanks for your contribution!

**Pull request merged**
